In [57]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
np.set_printoptions(threshold=np.inf)

In [58]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

## Scholarship Portal 

In [59]:
dataset = pd.read_csv('water_supply/water_supply.csv')
dataset

Grievance Subject  Issue with - Drinking/Supply Parts needed  \
0           Not Reqd                      Drinking          Tap   
1           Not Reqd                      Drinking          Tap   
2           Not Reqd                        Supply          Tap   
3           Not Reqd                        Supply          Tap   
4           Not Reqd                      Drinking         Pipe   
5           Not Reqd                      Drinking          Tap   
6           Not Reqd                      Drinking          Tap   
7           Not Reqd                      Drinking         Pipe   
8           Not Reqd                        Supply      Bassers   
9           Not Reqd                        Supply      Bassers   
10          Not Reqd                      Drinking      Bassers   
11          Not Reqd                        Supply          Tap   
12          Not Reqd                      Drinking         Pipe   
13          Not Reqd                        Supply         Pipe   
14          Not Reqd                      Drinking          Tap   
15          Not Reqd                        Supply          Tap   
16          Not Reqd                        Supply          Tap   
17          Not Reqd                        Supply          Tap   
18          Not Reqd                        Supply      Bassers   
19          Not Reqd                        Supply         Pipe   
20          Not Reqd                      Drinking         Pipe   
21          Not Reqd                        Supply         Pipe   
22          Not Reqd                        Supply          Tap   
23          Not Reqd                      Drinking         Pipe   
24          Not Reqd                        Supply         Pipe   
25          Not Reqd                      Drinking         Pipe   
26          Not Reqd                        Supply      Bassers   
27          Not Reqd                      Drinking         Pipe   
28          Not Reqd                      Drinking          Tap   
29          Not Reqd                        Supply          Tap   
30          Not Reqd                      Drinking          Tap   
31          Not Reqd                        Supply      Bassers   
32          Not Reqd                        Supply          Tap   
33          Not Reqd                        Supply          Tap   
34          Not Reqd                        Supply          Tap   
35          Not Reqd                        Supply          Tap   
36          Not Reqd                        Supply          Tap   
37          Not Reqd                      Drinking      Bassers   
38          Not Reqd                      Drinking         Pipe   
39          Not Reqd                      Drinking         Pipe   
40          Not Reqd                      Drinking      Bassers   
41          Not Reqd                        Supply         Pipe   
42          Not Reqd                        Supply          Tap   
43          Not Reqd                      Drinking         Pipe   
44          Not Reqd                        Supply         Pipe   
45          Not Reqd                      Drinking          Tap   
46          Not Reqd                      Drinking          Tap   
47          Not Reqd                      Drinking      Bassers   
48          Not Reqd                        Supply         Pipe   

    Quantity of Parts - (OFP) Availablity - Available/Need to Order - (OFP)  \
0                          15                                 Need To Order   
1                           7                                 Need To Order   
2                          19                                 Need To Order   
3                           4                                     Available   
4                          14                                     Available   
5                          25                                 Need To Order   
6                          29                                     Available   
7                   

In [60]:
k = [1,2,3,4,5]
df = dataset.iloc[:, k] 
X = dataset.iloc[:, k].values
Y = dataset.iloc[:, 8].values
len(X[0])
df

Issue with - Drinking/Supply Parts needed  Quantity of Parts - (OFP)  \
0                       Drinking          Tap                         15   
1                       Drinking          Tap                          7   
2                         Supply          Tap                         19   
3                         Supply          Tap                          4   
4                       Drinking         Pipe                         14   
5                       Drinking          Tap                         25   
6                       Drinking          Tap                         29   
7                       Drinking         Pipe                         10   
8                         Supply      Bassers                         13   
9                         Supply      Bassers                          2   
10                      Drinking      Bassers                         21   
11                        Supply          Tap                          6   
12                      Drinking         Pipe                         26   
13                        Supply         Pipe                         14   
14                      Drinking          Tap                         22   
15                        Supply          Tap                         15   
16                        Supply          Tap                         20   
17                        Supply          Tap                         13   
18                        Supply      Bassers                         20   
19                        Supply         Pipe                          7   
20                      Drinking         Pipe                         21   
21                        Supply         Pipe                          5   
22                        Supply          Tap                         12   
23                      Drinking         Pipe                          9   
24                        Supply         Pipe                         19   
25                      Drinking         Pipe                          8   
26                        Supply      Bassers                         23   
27                      Drinking         Pipe                         22   
28                      Drinking          Tap                         24   
29                        Supply          Tap                          4   
30                      Drinking          Tap                         14   
31                        Supply      Bassers                         18   
32                        Supply          Tap                         26   
33                        Supply          Tap                         25   
34                        Supply          Tap                         19   
35                        Supply          Tap                         16   
36                        Supply          Tap                         30   
37                      Drinking      Bassers                         10   
38                      Drinking         Pipe                         29   
39                      Drinking         Pipe                         16   
40                      Drinking      Bassers                         11   
41                        Supply         Pipe                          8   
42                        Supply          Tap                         19   
43                      Drinking         Pipe                          3   
44                        Supply         Pipe                         24   
45                      Drinking          Tap                          8   
46                      Drinking          Tap                         27   
47                      Drinking      Bassers                         12   
48                        Supply         Pipe                         25   

   Availablity - Available/Need to Order - (OFP)  \
0                                  Need To Order   
1                                  Need To Order   
2                                  Need To Orde

In [61]:
# Save Encoder Objects for new incoming data
import pickle
encx0 = LabelEncoder().fit(X[:,0])
encx1 = LabelEncoder().fit(X[:,1])
encx3 = LabelEncoder().fit(X[:,3])
encx4 = LabelEncoder().fit(X[:,4])
filename = 'water_supply/watersupplyencx0.sav'
pickle.dump(encx0,open(filename,'wb'))
filename = 'water_supply/watersupplyencx1.sav'
pickle.dump(encx1,open(filename,'wb'))
filename = 'water_supply/watersupplyencx3.sav'
pickle.dump(encx3,open(filename,'wb'))
filename = 'water_supply/watersupplyencx4.sav'
pickle.dump(encx4,open(filename,'wb'))

In [62]:
data = ['Drinking','Pipe',3,'Available','No']

In [63]:
X[:,0] = encx0.transform(X[:,0])
X[:,1] = encx1.transform(X[:,1])
X[:,3] = encx3.transform(X[:,3])
X[:,4] = encx4.transform(X[:,4])

In [98]:
print(max(X[:,1]))

1.0


In [65]:
onehotencoder = OneHotEncoder(categorical_features=[0,1,3,4])
onehenc = onehotencoder.fit(X)
filename = 'water_supply/water_supplyonehenc.sav'
pickle.dump(onehenc,open(filename,'wb'))
X = onehenc.transform(X).toarray()
d = encx0.transform([data[0]])
data[0] = d[0]
d = encx1.transform([data[1]])
data[1] = d[0]
d = encx3.transform([data[3]])
data[3] = d[0]
d = encx4.transform([data[4]])
data[4] = d[0]
ar = np.array(data)
print(data)
ar = ar.reshape(1,-1)
kar=onehenc.transform(ar).toarray()
print(kar)
print(len(X[0]))

[0, 1, 3, 0, 0]
[[1. 0. 0. 1. 0. 1. 0. 1. 0. 3.]]
10


In [66]:
k = list()
notlist = [0,2,5,7]
for i in range(10):
    if i not in notlist:
        k.append(i)
X = X[:,k]
kar = kar[:,k]

In [67]:
print(len(X[0]))

6


## SVR

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [70]:
model1 = SVR(kernel='rbf')
model1.fit(X_train,Y_train)
Y_pred = model1.predict(X_test)

In [71]:
Y_pred

array([5.33840943, 4.97953718, 4.1835386 , 5.27710442, 4.21209584,
       5.40729348, 7.22266659, 5.34536141, 5.40865921, 5.66718552])

In [72]:
Y_test

array([7, 8, 2, 7, 3, 6, 7, 3, 5, 4])

In [44]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C':[1,10,100,1000], 'kernel': ['rbf'], 'gamma':[0.05,0.01,0.001,0.0001]},
             {'C':[100,200,300,400], 'kernel': ['poly'], 'gamma':[0.05,0.06,0.07,0.08,0.09,0.1]},
             {'C':[1,10,100,1000], 'kernel': ['sigmoid'], 'gamma':[0.05,0.01,0.001,0.0001]}]
gridsearch = GridSearchCV(estimator=model1,
                         param_grid=parameters,
                         scoring='r2',
                         cv=10)
gridsearch = gridsearch.fit(X_train,Y_train)
print(gridsearch.best_score_)
print(gridsearch.best_params_)

KeyboardInterrupt: 

## Random Forest

In [80]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [93]:
model2 = RandomForestRegressor(n_estimators=700, criterion='mse',random_state=0)
model2 = model2.fit(X,Y)

In [94]:
from sklearn.metrics import r2_score
Y_pred = model2.predict(X)
print(Y_pred)
print(Y_test)
print(r2_score(Y,Y_pred))

[6.43       5.06428571 7.89142857 4.81285714 7.01714286 4.05714286
 4.85571429 5.27285714 3.85285714 6.61428571 4.76714286 5.94285714
 5.79285714 4.54428571 3.89142857 7.31142857 8.44857143 4.03
 6.39857143 4.33857143 5.48428571 5.14571429 5.26285714 6.13857143
 4.73285714 4.42       2.75857143 4.27857143 5.67857143 6.25142857
 6.48428571 6.5        3.63142857 3.97       7.18       7.43428571
 6.11714286 5.77142857 5.36571429 4.70428571 4.03142857 4.90285714
 7.89142857 5.75857143 3.48857143 3.96       4.11714286 6.73428571
 3.78857143]
[7 8 2 7 3 6 7 3 5 4]
0.8650034709906258


In [79]:
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators':[10,20,30,40,60,70,80,90,100], 'criterion':['mse','mae']}]
grid_search = GridSearchCV(estimator=model2,
                          param_grid=parameters,
                          scoring='r2',
                          cv=10)
grid_search = grid_search.fit(X,Y)
print(grid_search.best_score_)
print(grid_search.best_params_)

-0.1648039911235912
{'criterion': 'mae', 'n_estimators': 40}


In [95]:
import pickle
filename = 'water_supply/water_supplymodel.sav'
pickle.dump(model2,open(filename,'wb'))

In [96]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(kar)
print(result)
from sklearn.metrics import r2_score

[5.31714286]


In [97]:
from sklearn.preprocessing import LabelEncoder
c = ['France', 'UK', 'US', 'US', 'UK', 'China', 'France']
enc = LabelEncoder().fit(c)
encoded = enc.transform(c)
print(encoded)

enc.transform(['France'])


[1 2 3 3 2 0 1]


array([1])