In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
np.set_printoptions(threshold=np.inf)

In [2]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


## Sports 

In [3]:
dataset = pd.read_csv('Sports/Sports.csv')
dataset

Grievance Subject Issue with - New Material/ Material Repair  \
0           Not Reqd                            Material Repair   
1           Not Reqd                               New Material   
2           Not Reqd                               New Material   
3           Not Reqd                            Material Repair   
4           Not Reqd                               New Material   
5           Not Reqd                               New Material   
6           Not Reqd                            Material Repair   
7           Not Reqd                            Material Repair   
8           Not Reqd                            Material Repair   
9           Not Reqd                            Material Repair   
10          Not Reqd                            Material Repair   
11          Not Reqd                            Material Repair   
12          Not Reqd                               New Material   
13          Not Reqd                            Material Repair   
14          Not Reqd                               New Material   
15          Not Reqd                               New Material   
16          Not Reqd                               New Material   
17          Not Reqd                               New Material   
18          Not Reqd                               New Material   
19          Not Reqd                            Material Repair   
20          Not Reqd                            Material Repair   
21          Not Reqd                            Material Repair   
22          Not Reqd                            Material Repair   
23          Not Reqd                            Material Repair   
24          Not Reqd                            Material Repair   
25          Not Reqd                               New Material   
26          Not Reqd                            Material Repair   
27          Not Reqd                               New Material   
28          Not Reqd                            Material Repair   
29          Not Reqd                            Material Repair   
30          Not Reqd                            Material Repair   
31          Not Reqd                            Material Repair   
32          Not Reqd                            Material Repair   
33          Not Reqd                               New Material   
34          Not Reqd                               New Material   
35          Not Reqd                            Material Repair   
36          Not Reqd                               New Material   
37          Not Reqd                               New Material   
38          Not Reqd                            Material Repair   
39          Not Reqd                            Material Repair   
40          Not Reqd                               New Material   
41          Not Reqd                               New Material   
42          Not Reqd                            Material Repair   
43          Not Reqd                            Material Repair   
44          Not Reqd                            Material Repair   
45          Not Reqd                            Material Repair   
46          Not Reqd                            Material Repair   
47          Not Reqd                               New Material   
48          Not Reqd                            Material Repair   

    Material Needed - (OFP) Availability - (OFP) Manpower required - (OFP)  \
0                         5        Need To Order                       Yes   
1                         1            Available                        No   
2                         3            Available                        No   
3                         1            Available                       Yes   
4                         3            Available                        No   
5                         4            Available                       Yes   
6                         7        Need To Order                        No   
7                         5 

In [4]:
k = [1,2,3,4,5]
df = dataset.iloc[:, k] 
X = dataset.iloc[:, k].values
Y = dataset.iloc[:, 6].values
len(X[0])
df

Issue with - New Material/ Material Repair  Material Needed - (OFP)  \
0                             Material Repair                        5   
1                                New Material                        1   
2                                New Material                        3   
3                             Material Repair                        1   
4                                New Material                        3   
5                                New Material                        4   
6                             Material Repair                        7   
7                             Material Repair                        5   
8                             Material Repair                        8   
9                             Material Repair                        1   
10                            Material Repair                        8   
11                            Material Repair                        6   
12                               New Material                        5   
13                            Material Repair                        7   
14                               New Material                        7   
15                               New Material                        6   
16                               New Material                        2   
17                               New Material                        3   
18                               New Material                        2   
19                            Material Repair                        3   
20                            Material Repair                        8   
21                            Material Repair                        6   
22                            Material Repair                        6   
23                            Material Repair                        1   
24                            Material Repair                        7   
25                               New Material                        2   
26                            Material Repair                        1   
27                               New Material                        6   
28                            Material Repair                        2   
29                            Material Repair                        1   
30                            Material Repair                        5   
31                            Material Repair                        5   
32                            Material Repair                        1   
33                               New Material                        3   
34                               New Material                        7   
35                            Material Repair                        3   
36                               New Material                        3   
37                               New Material                        2   
38                            Material Repair                        2   
39                            Material Repair                        1   
40                               New Material                        5   
41                               New Material                        8   
42                            Material Repair                        8   
43                            Material Repair                        4   
44                            Material Repair                        6   
45                            Material Repair                        8   
46                            Material Repair                        8   
47                               New Material                        2   
48                            Material Repair                        2   

   Availability - (OFP) Manpower required - (OFP)  \
0         Need To Order                       Yes   
1             Available                        No   
2             Available                        No   
3             Available                       Yes   
4             Available              

In [5]:
# Save Encoder Objects for new incoming data
import pickle
encx0 = LabelEncoder().fit(X[:,0])
encx2 = LabelEncoder().fit(X[:,2])
encx3 = LabelEncoder().fit(X[:,3])
encx4 = LabelEncoder().fit(X[:,4])
filename = 'Sports/Sportsencx0.sav'
pickle.dump(encx0,open(filename,'wb'))
filename = 'Sports/Sportsencx2.sav'
pickle.dump(encx2,open(filename,'wb'))
filename = 'Sports/Sportsencx3.sav'
pickle.dump(encx3,open(filename,'wb'))
filename = 'Sports/Sportsencx4.sav'
pickle.dump(encx4,open(filename,'wb'))

In [6]:
data = ['Material Repair',3,'Available','Yes','No']

In [7]:
X[:,0] = encx0.transform(X[:,0])
X[:,2] = encx2.transform(X[:,2])
X[:,3] = encx3.transform(X[:,3])
X[:,4] = encx4.transform(X[:,4])

In [8]:
print(max(X[:,2]))

1


In [9]:
onehotencoder = OneHotEncoder(categorical_features=[0,2,3,4])
onehenc = onehotencoder.fit(X)
filename = 'Sports/Sportsonehenc.sav'
pickle.dump(onehenc,open(filename,'wb'))
X = onehenc.transform(X).toarray()
d = encx0.transform([data[0]])
data[0] = d[0]
d = encx2.transform([data[2]])
data[2] = d[0]
d = encx3.transform([data[3]])
data[3] = d[0]
d = encx4.transform([data[4]])
data[4] = d[0]
ar = np.array(data)
print(data)
ar = ar.reshape(1,-1)
kar=onehenc.transform(ar).toarray()
print(kar)
print(len(X[0]))

[0, 3, 0, 1, 0]
[[1. 0. 1. 0. 0. 1. 1. 0. 3.]]
9


In [10]:
k = list()
notlist = [0,2,4,6]
for i in range(9):
    if i not in notlist:
        k.append(i)
X = X[:,k]
kar = kar[:,k]

In [11]:
print(len(X[0]))

5


## SVR

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [14]:
model1 = SVR(kernel='rbf')
model1.fit(X_train,Y_train)
Y_pred = model1.predict(X_test)

In [15]:
Y_pred

array([6.70242794, 8.10033553, 6.8960786 , 7.38619484, 6.70242794,
       7.20515351, 7.04492355, 6.81858727, 6.10006658, 8.90010878])

In [16]:
Y_test

array([13,  8, 10,  7, 13,  5, 11,  7,  6,  9])

In [17]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C':[1,10,100,1000], 'kernel': ['rbf'], 'gamma':[0.05,0.01,0.001,0.0001]},
             {'C':[100,200,300,400], 'kernel': ['poly'], 'gamma':[0.05,0.06,0.07,0.08,0.09,0.1]},
             {'C':[1,10,100,1000], 'kernel': ['sigmoid'], 'gamma':[0.05,0.01,0.001,0.0001]}]
gridsearch = GridSearchCV(estimator=model1,
                         param_grid=parameters,
                         scoring='r2',
                         cv=10)
gridsearch = gridsearch.fit(X_train,Y_train)
print(gridsearch.best_score_)
print(gridsearch.best_params_)

-0.4022148212223908
{'C': 1, 'gamma': 0.05, 'kernel': 'sigmoid'}


## Random Forest

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [19]:
model2 = RandomForestRegressor(n_estimators=700, criterion='mse',random_state=0)
model2 = model2.fit(X,Y)

In [20]:
from sklearn.metrics import r2_score
Y_pred = model2.predict(X)
for i in Y_pred:
    print(round(i))
print(Y_test)
print(r2_score(Y,Y_pred))

8.0
5.0
8.0
4.0
8.0
9.0
4.0
6.0
9.0
7.0
9.0
4.0
6.0
6.0
5.0
6.0
6.0
11.0
7.0
8.0
9.0
7.0
10.0
9.0
8.0
6.0
10.0
4.0
7.0
12.0
8.0
6.0
12.0
11.0
10.0
11.0
9.0
5.0
8.0
4.0
7.0
8.0
10.0
11.0
4.0
11.0
10.0
7.0
10.0
[13  8 10  7 13  5 11  7  6  9]
0.9289590754308121


In [21]:
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators':[1,10,100,1000], 'criterion':['mse','mae']}]
grid_search = GridSearchCV(estimator=model2,
                          param_grid=parameters,
                          scoring='r2',
                          cv=10)
grid_search = grid_search.fit(X,Y)
print(grid_search.best_score_)
print(grid_search.best_params_)

0.1796326675702437
{'criterion': 'mae', 'n_estimators': 1000}


In [22]:
import pickle
filename = 'Sports/Sportsmodel.sav'
pickle.dump(model2,open(filename,'wb'))

In [23]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(kar)
print(result)
from sklearn.metrics import r2_score

[10.30857143]


In [24]:
from sklearn.preprocessing import LabelEncoder
c = ['France', 'UK', 'US', 'US', 'UK', 'China', 'France']
enc = LabelEncoder().fit(c)
encoded = enc.transform(c)
print(encoded)

enc.transform(['France'])


[1 2 3 3 2 0 1]


array([1])

## Classification

In [25]:
Y2=dataset.iloc[:,-1].values

In [26]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [30]:
classifier = RandomForestClassifier(n_estimators=1000, criterion='gini')
classifier = classifier.fit(X,Y2)
y_pred = classifier.predict(X)
print(classification_report(Y2,y_pred))

             precision    recall  f1-score   support

     Major        0.86      0.90      0.88        20
      Minor       0.93      0.90      0.91        29

avg / total       0.90      0.90      0.90        49



In [31]:
parameters = [{'n_estimators':[1,10,100,1000], 'criterion':['gini', 'entropy']}]
grid_search = GridSearchCV(estimator=classifier,
                          param_grid=parameters,
                          scoring='accuracy')
grid_search = grid_search.fit(X,Y)
print(grid_search.best_score_)
print(grid_search.best_params_)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:605: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


0.3469387755102041
{'criterion': 'gini', 'n_estimators': 10}


In [32]:
filename = 'Sports/SportsClassmodel.sav'
pickle.dump(classifier,open(filename,'wb'))