In [230]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
np.set_printoptions(threshold=np.inf)

In [231]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

## Mess (Hr) 

In [232]:
dataset = pd.read_csv('Mess(hr)/Mess(hr).csv')
dataset

Grievance Subject Hostel Transaction Mode Bank used by Payee  \
0           Not Reqd      N           CHEQUE              ICICI   
1           Not Reqd      I           CHEQUE               HDFC   
2           Not Reqd      I             NEFT               HDFC   
3           Not Reqd      L            PAYTM               HDFC   
4           Not Reqd      B             NEFT               HDFC   
5           Not Reqd      H           CHEQUE              ICICI   
6           Not Reqd     PG           CHEQUE              ICICI   
7           Not Reqd      A               DD              ICICI   
8           Not Reqd      L           CHEQUE                SBI   
9           Not Reqd      I             NEFT                SBI   
10          Not Reqd      H          CHALLAN              ICICI   
11          Not Reqd      N             NEFT              ICICI   
12          Not Reqd      N           CHEQUE               HDFC   
13          Not Reqd      K          CHALLAN                SBI   
14          Not Reqd     PG             NEFT              ICICI   
15          Not Reqd      K               DD              ICICI   
16          Not Reqd      B               DD                SBI   
17          Not Reqd      E            PAYTM                SBI   
18          Not Reqd      N           CHEQUE               HDFC   
19          Not Reqd      H           CHEQUE                SBI   
20          Not Reqd      K               DD              ICICI   
21          Not Reqd      I             NEFT               HDFC   
22          Not Reqd      B             NEFT               HDFC   
23          Not Reqd      H             NEFT              ICICI   
24          Not Reqd      L            PAYTM                SBI   
25          Not Reqd      M           CHEQUE               HDFC   
26          Not Reqd      N               DD               HDFC   
27          Not Reqd      I               DD                SBI   
28          Not Reqd      L            PAYTM               HDFC   
29          Not Reqd      K           CHEQUE              ICICI   
30          Not Reqd      I             NEFT               HDFC   
31          Not Reqd      L           CHEQUE                SBI   
32          Not Reqd      K           CHEQUE                SBI   
33          Not Reqd      L          CHALLAN              ICICI   
34          Not Reqd      J            PAYTM                SBI   
35          Not Reqd      I               DD              ICICI   
36          Not Reqd     PG            PAYTM              ICICI   
37          Not Reqd      L           CHEQUE               HDFC   
38          Not Reqd      A             NEFT               HDFC   
39          Not Reqd      A           CHEQUE              ICICI   
40          Not Reqd      G            PAYTM                SBI   
41          Not Reqd      N             NEFT              ICICI   
42          Not Reqd      A             NEFT               HDFC   
43          Not Reqd      H           CHEQUE               HDFC   
44          Not Reqd      B            PAYTM                SBI   
45          Not Reqd      E           CHEQUE                SBI   
46          Not Reqd      G          CHALLAN                SBI   
47          Not Reqd      I           CHEQUE                SBI   
48          Not Reqd      H             NEFT              ICICI   

    Transaction Number  Account Number of Payee Grievance Description  \
0           1761066513             955710000000              Not Reqd   
1           1893755115             919483000000              Not Reqd   
2           1775178520             946425000000              Not Reqd   
3           1010544585             924271000000              Not Reqd   
4           1296796242             990537000000              Not Reqd   
5           1701715302             915368000000              Not Reqd   
6           1612845749             902984000000              Not Reqd   
7           1831049838             922215000000              Not Req

In [233]:
X = dataset.iloc[:, 1:4].values
Y = dataset.iloc[:, 8].values

In [234]:
# Save Encoder Objects for new incoming data
import pickle
encx0 = LabelEncoder().fit(X[:,0])
encx1 = LabelEncoder().fit(X[:,1])
encx2 = LabelEncoder().fit(X[:,2])
filename = 'Mess(hr)/Mess(hr)encx0.sav'
pickle.dump(encx0,open(filename,'wb'))
filename = 'Mess(hr)/Mess(hr)encx1.sav'
pickle.dump(encx1,open(filename,'wb'))
filename = 'Mess(hr)/Mess(hr)encx2.sav'
pickle.dump(encx2,open(filename,'wb'))

In [235]:
X[:,0] = encx0.transform(X[:,0])
X[:,1] = encx1.transform(X[:,1])
X[:,2] = encx2.transform(X[:,2])
onehotencoder = OneHotEncoder(categorical_features=[0,1,2])
onehenc = onehotencoder.fit(X)
filename = 'Mess(hr)/Mess(hr)onehenc.sav'
pickle.dump(onehenc,open(filename,'wb'))
X = onehenc.transform(X).toarray()
ar = np.array([10,1,1])
ar = ar.reshape(1,-1)
kar=onehenc.transform(ar).toarray()
print(kar)
print(len(X[0]))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0.]]
20


In [236]:
k = list()
for i in range(20):
    if i!=0 and i!=12 and i!=17:
        k.append(i)
X = X[:,k]
kar = kar[:,k]

In [237]:
print(len(X[0]))

17


## SVR

In [238]:
from sklearn.model_selection import train_test_split

In [239]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [240]:
model1 = SVR(kernel='rbf')
model1.fit(X_train,Y_train)
Y_pred = model1.predict(X_test)

In [241]:
Y_pred

array([8.92320151, 8.83116842, 9.17595093, 8.46880509, 9.0988148 ,
       8.4140806 , 8.65264704, 8.75729675, 8.98116298, 8.16155869])

In [242]:
Y_test

array([13, 10,  9,  6, 11,  7,  9, 10, 12,  8])

In [243]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C':[1,10,100,1000], 'kernel': ['rbf'], 'gamma':[0.05,0.01,0.001,0.0001]},
             {'C':[100,200,300,400], 'kernel': ['poly'], 'gamma':[0.05,0.06,0.07,0.08,0.09,0.1]},
             {'C':[1,10,100,1000], 'kernel': ['sigmoid'], 'gamma':[0.05,0.01,0.001,0.0001]}]
gridsearch = GridSearchCV(estimator=model1,
                         param_grid=parameters,
                         scoring='r2',
                         cv=10)
gridsearch = gridsearch.fit(X_train,Y_train)
print(gridsearch.best_score_)
print(gridsearch.best_params_)

0.044359634022896555
{'C': 1000, 'gamma': 0.001, 'kernel': 'rbf'}


## Random Forest

In [244]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [245]:
model2 = RandomForestRegressor(n_estimators=970, criterion='mse',random_state=0)
model2 = model2.fit(X,Y)

In [246]:
Y_pred = model2.predict(X_test)
print(Y_pred)
print(Y_test)

[12.72680412  9.92783505  9.18865979  6.18556701 11.02061856  6.91958763
  9.02268041 10.03917526 11.67835052  7.45360825]
[13 10  9  6 11  7  9 10 12  8]


In [247]:
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators':[950,960,970,980,990,1000], 'criterion':['mse']}]
grid_search = GridSearchCV(estimator=model2,
                          param_grid=parameters,
                          scoring='r2',
                          cv=10)
grid_search = grid_search.fit(X,Y)
print(grid_search.best_score_)
print(grid_search.best_params_)

0.5025834689186863
{'criterion': 'mse', 'n_estimators': 970}


In [248]:
import pickle
filename = 'Mess(hr)/Mess(hr)model.sav'
pickle.dump(model2,open(filename,'wb'))

In [249]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(kar)
print(result)
from sklearn.metrics import r2_score
print(r2_score(Y_test,Y_pred))

[10.66494845]
0.9868043737847992


In [207]:
from sklearn.preprocessing import LabelEncoder
c = ['France', 'UK', 'US', 'US', 'UK', 'China', 'France']
enc = LabelEncoder().fit(c)
encoded = enc.transform(c)
print(encoded)

enc.transform(['France'])


[1 2 3 3 2 0 1]


array([1])