In [47]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
np.set_printoptions(threshold=np.inf)

In [48]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

## Roads 

In [49]:
dataset = pd.read_csv('Roads/Roads.csv')
dataset

Grievance Subject Issue with - New Road/ Road Repair  \
0           Not Reqd                        Road Repair   
1           Not Reqd                        Road Repair   
2           Not Reqd                           New Road   
3           Not Reqd                           New Road   
4           Not Reqd                        Road Repair   
5           Not Reqd                           New Road   
6           Not Reqd                           New Road   
7           Not Reqd                           New Road   
8           Not Reqd                           New Road   
9           Not Reqd                           New Road   
10          Not Reqd                           New Road   
11          Not Reqd                           New Road   
12          Not Reqd                        Road Repair   
13          Not Reqd                           New Road   
14          Not Reqd                           New Road   
15          Not Reqd                        Road Repair   
16          Not Reqd                        Road Repair   
17          Not Reqd                           New Road   
18          Not Reqd                        Road Repair   
19          Not Reqd                        Road Repair   
20          Not Reqd                        Road Repair   
21          Not Reqd                        Road Repair   
22          Not Reqd                           New Road   
23          Not Reqd                           New Road   
24          Not Reqd                        Road Repair   
25          Not Reqd                           New Road   
26          Not Reqd                        Road Repair   
27          Not Reqd                           New Road   
28          Not Reqd                           New Road   
29          Not Reqd                           New Road   
30          Not Reqd                           New Road   
31          Not Reqd                           New Road   
32          Not Reqd                        Road Repair   
33          Not Reqd                        Road Repair   
34          Not Reqd                           New Road   
35          Not Reqd                           New Road   
36          Not Reqd                           New Road   
37          Not Reqd                        Road Repair   
38          Not Reqd                           New Road   
39          Not Reqd                        Road Repair   
40          Not Reqd                           New Road   
41          Not Reqd                        Road Repair   
42          Not Reqd                           New Road   
43          Not Reqd                        Road Repair   
44          Not Reqd                        Road Repair   
45          Not Reqd                        Road Repair   
46          Not Reqd                           New Road   
47          Not Reqd                           New Road   
48          Not Reqd                           New Road   

    Material Needed - (OFP) Availability - (OFP) Manpower required - (OFP)  \
0                        20        Need To Order                        No   
1                        15        Need To Order                       Yes   
2                         7            Available                       Yes   
3                        45        Need To Order                        No   
4                        48            Available                        No   
5                        26        Need To Order                        No   
6                        12            Available                       Yes   
7                         6        Need To Order                       Yes   
8                        23            Available                       Yes   
9                        46        Need To Order                       Yes   
10                        3        Need To Order                        No   
11                        7        Need To Order                       Yes   
12                       89           

In [50]:
k = [1,2,3,4,5]
df = dataset.iloc[:, k] 
X = dataset.iloc[:, k].values
Y = dataset.iloc[:, 7].values
len(X[0])
df

Issue with - New Road/ Road Repair  Material Needed - (OFP)  \
0                         Road Repair                       20   
1                         Road Repair                       15   
2                            New Road                        7   
3                            New Road                       45   
4                         Road Repair                       48   
5                            New Road                       26   
6                            New Road                       12   
7                            New Road                        6   
8                            New Road                       23   
9                            New Road                       46   
10                           New Road                        3   
11                           New Road                        7   
12                        Road Repair                       89   
13                           New Road                        2   
14                           New Road                        1   
15                        Road Repair                       62   
16                        Road Repair                       32   
17                           New Road                       47   
18                        Road Repair                       12   
19                        Road Repair                       32   
20                        Road Repair                        5   
21                        Road Repair                        4   
22                           New Road                       45   
23                           New Road                        7   
24                        Road Repair                        9   
25                           New Road                       79   
26                        Road Repair                       97   
27                           New Road                       54   
28                           New Road                        2   
29                           New Road                        6   
30                           New Road                       62   
31                           New Road                       26   
32                        Road Repair                       13   
33                        Road Repair                        1   
34                           New Road                        3   
35                           New Road                       31   
36                           New Road                       64   
37                        Road Repair                       46   
38                           New Road                        6   
39                        Road Repair                        4   
40                           New Road                       51   
41                        Road Repair                       15   
42                           New Road                        1   
43                        Road Repair                        5   
44                        Road Repair                        8   
45                        Road Repair                        3   
46                           New Road                       38   
47                           New Road                       83   
48                           New Road                       16   

   Availability - (OFP) Manpower required - (OFP)  \
0         Need To Order                        No   
1         Need To Order                       Yes   
2             Available                       Yes   
3         Need To Order                        No   
4             Available                        No   
5         Need To Order                        No   
6             Available                       Yes   
7         Need To Order                       Yes   
8             Available                       Yes   
9         Need To Order                       Yes   
10        Need To Order                        No   
11        Need To Order                       Yes   
12           

In [51]:
# Save Encoder Objects for new incoming data
import pickle
encx0 = LabelEncoder().fit(X[:,0])
encx2 = LabelEncoder().fit(X[:,2])
encx3 = LabelEncoder().fit(X[:,3])
encx4 = LabelEncoder().fit(X[:,4])
filename = 'Roads/Roadsencx0.sav'
pickle.dump(encx0,open(filename,'wb'))
filename = 'Roads/Roadsencx2.sav'
pickle.dump(encx2,open(filename,'wb'))
filename = 'Roads/Roadsencx3.sav'
pickle.dump(encx3,open(filename,'wb'))
filename = 'Roads/Roadsencx4.sav'
pickle.dump(encx4,open(filename,'wb'))

In [52]:
data = ['Road Repair',5,'Available','No','Yes']

In [53]:
X[:,0] = encx0.transform(X[:,0])
X[:,2] = encx2.transform(X[:,2])
X[:,3] = encx3.transform(X[:,3])
X[:,4] = encx4.transform(X[:,4])

In [54]:
print(max(X[:,0]))

1


In [55]:
onehotencoder = OneHotEncoder(categorical_features=[0,2,3,4])
onehenc = onehotencoder.fit(X)
filename = 'Roads/Roadsonehenc.sav'
pickle.dump(onehenc,open(filename,'wb'))
X = onehenc.transform(X).toarray()
d = encx0.transform([data[0]])
data[0] = d[0]
d = encx2.transform([data[2]])
data[2] = d[0]
d = encx3.transform([data[3]])
data[3] = d[0]
d = encx3.transform([data[4]])
data[4] = d[0]
ar = np.array(data)
print(data)
ar = ar.reshape(1,-1)
kar=onehenc.transform(ar).toarray()
print(kar)
print(len(X[0]))

[1, 5, 0, 0, 1]
[[0. 1. 1. 0. 1. 0. 0. 1. 5.]]
9


In [56]:
k = list()
notlist = [0,2,4,6]
for i in range(9):
    if i not in notlist:
        k.append(i)
X = X[:,k]
kar = kar[:,k]

In [57]:
print((kar[0]))

[1. 0. 0. 1. 5.]


## SVR

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [60]:
model1 = SVR(kernel='rbf')
model1.fit(X_train,Y_train)
Y_pred = model1.predict(X_test)

In [61]:
Y_pred

array([22.89970197, 22.25833662, 22.49163238, 22.14971309, 21.69687736,
       22.90553953, 21.97704394, 22.29831611, 22.89970197, 21.97704394])

In [62]:
Y_test

array([23, 25, 24, 22, 18, 28, 19, 19, 23, 19])

In [63]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C':[1,10,100,1000], 'kernel': ['rbf'], 'gamma':[0.05,0.01,0.001,0.0001]}]
gridsearch = GridSearchCV(estimator=model1,
                         param_grid=parameters,
                         scoring='r2',
                         cv=10)
gridsearch = gridsearch.fit(X_train,Y_train)
print(gridsearch.best_score_)
print(gridsearch.best_params_)

-0.2623808285022851
{'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}


## Random Forest

In [64]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [65]:
model2 = RandomForestRegressor(n_estimators=1000, criterion='mse',random_state=0)
model2 = model2.fit(X,Y)

In [66]:
from sklearn.metrics import r2_score
Y_pred = model2.predict(X)
for i in Y_pred:
    print(round(i))
print(Y_test)
print(r2_score(Y,Y_pred))

25.0
21.0
22.0
26.0
25.0
26.0
19.0
23.0
22.0
24.0
19.0
23.0
24.0
22.0
23.0
23.0
25.0
21.0
21.0
22.0
19.0
21.0
20.0
23.0
22.0
23.0
22.0
17.0
21.0
23.0
22.0
22.0
19.0
19.0
19.0
23.0
17.0
27.0
23.0
22.0
19.0
23.0
22.0
21.0
21.0
22.0
26.0
24.0
20.0
[23 25 24 22 18 28 19 19 23 19]
0.9232890575803321


In [69]:
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators':[1,10,100,1000], 'criterion':['mse','mae']}]
grid_search = GridSearchCV(estimator=model2,
                          param_grid=parameters,
                          scoring='r2',
                          cv=10)
grid_search = grid_search.fit(X,Y)
print(grid_search.best_score_)
print(grid_search.best_params_)

0.18067713267804722
{'criterion': 'mse', 'n_estimators': 1000}


In [70]:
import pickle
filename = 'Roads/Roadsmodel.sav'
pickle.dump(model2,open(filename,'wb'))

In [71]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(kar)
print(result)
from sklearn.metrics import r2_score

[20.944]


In [72]:
from sklearn.preprocessing import LabelEncoder
c = ['France', 'UK', 'US', 'US', 'UK', 'China', 'France']
enc = LabelEncoder().fit(c)
encoded = enc.transform(c)
print(encoded)

enc.transform(['France'])


[1 2 3 3 2 0 1]


array([1])