In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
np.set_printoptions(threshold=np.inf)

In [3]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


## Electricity 

In [4]:
dataset = pd.read_csv('WIFI/WIFI.csv')
dataset

Grievance Subject Issue with - Speed/ Range/ Connectivity  \
0           Not Reqd                            Connectivity   
1           Not Reqd                                   Range   
2           Not Reqd                            Connectivity   
3           Not Reqd                                   Speed   
4           Not Reqd                            Connectivity   
5           Not Reqd                            Connectivity   
6           Not Reqd                                   Speed   
7           Not Reqd                            Connectivity   
8           Not Reqd                            Connectivity   
9           Not Reqd                                   Speed   
10          Not Reqd                                   Speed   
11          Not Reqd                                   Speed   
12          Not Reqd                            Connectivity   
13          Not Reqd                                   Range   
14          Not Reqd                            Connectivity   
15          Not Reqd                            Connectivity   
16          Not Reqd                                   Range   
17          Not Reqd                            Connectivity   
18          Not Reqd                                   Range   
19          Not Reqd                                   Range   
20          Not Reqd                                   Range   
21          Not Reqd                            Connectivity   
22          Not Reqd                                   Speed   
23          Not Reqd                            Connectivity   
24          Not Reqd                                   Range   
25          Not Reqd                                   Speed   
26          Not Reqd                            Connectivity   
27          Not Reqd                                   Speed   
28          Not Reqd                                   Range   
29          Not Reqd                                   Range   
30          Not Reqd                                   Range   
31          Not Reqd                                   Speed   
32          Not Reqd                                   Range   
33          Not Reqd                            Connectivity   
34          Not Reqd                                   Range   
35          Not Reqd                            Connectivity   
36          Not Reqd                            Connectivity   
37          Not Reqd                                   Speed   
38          Not Reqd                                   Speed   
39          Not Reqd                                   Range   
40          Not Reqd                                   Range   
41          Not Reqd                                   Speed   
42          Not Reqd                                   Speed   
43          Not Reqd                                   Speed   
44          Not Reqd                                   Speed   
45          Not Reqd                                   Speed   
46          Not Reqd                                   Speed   
47          Not Reqd                                   Range   
48          Not Reqd                            Connectivity   

   Problem Area - (OFP) Need for replacement - (OFP) Availability - (OFP)  \
0            WIFIRouter                          Yes        Need To Order   
1             Bandwidth                          Yes        Need To Order   
2            WIFIRouter                          Yes        Need To Order   
3             Bandwidth                          Yes        Need To Order   
4                 Ports                           No            Available   
5              Lan Wire                           No            Available   
6             Bandwidth                          Yes        Need To Order   
7              Lan Wire                           No            Available   
8                 Ports                          Yes            Available   
9              Lan Wire         

In [5]:
k = [1,2,3,4]
df = dataset.iloc[:, k] 
X = dataset.iloc[:, k].values
Y = dataset.iloc[:, 6].values
len(X[0])
df

Issue with - Speed/ Range/ Connectivity Problem Area - (OFP)  \
0                             Connectivity           WIFIRouter   
1                                    Range            Bandwidth   
2                             Connectivity           WIFIRouter   
3                                    Speed            Bandwidth   
4                             Connectivity                Ports   
5                             Connectivity             Lan Wire   
6                                    Speed            Bandwidth   
7                             Connectivity             Lan Wire   
8                             Connectivity                Ports   
9                                    Speed             Lan Wire   
10                                   Speed             Lan Wire   
11                                   Speed             Lan Wire   
12                            Connectivity           WIFIRouter   
13                                   Range            Bandwidth   
14                            Connectivity             Lan Wire   
15                            Connectivity             Lan Wire   
16                                   Range                Ports   
17                            Connectivity             Lan Wire   
18                                   Range           WIFIRouter   
19                                   Range             Lan Wire   
20                                   Range           WIFIRouter   
21                            Connectivity                Ports   
22                                   Speed                Ports   
23                            Connectivity             Lan Wire   
24                                   Range             Lan Wire   
25                                   Speed            Bandwidth   
26                            Connectivity                Ports   
27                                   Speed           WIFIRouter   
28                                   Range                Ports   
29                                   Range            Bandwidth   
30                                   Range                Ports   
31                                   Speed            Bandwidth   
32                                   Range            Bandwidth   
33                            Connectivity             Lan Wire   
34                                   Range            Bandwidth   
35                            Connectivity           WIFIRouter   
36                            Connectivity             Lan Wire   
37                                   Speed           WIFIRouter   
38                                   Speed           WIFIRouter   
39                                   Range                Ports   
40                                   Range                Ports   
41                                   Speed             Lan Wire   
42                                   Speed            Bandwidth   
43                                   Speed           WIFIRouter   
44                                   Speed                Ports   
45                                   Speed                Ports   
46                                   Speed           WIFIRouter   
47                                   Range             Lan Wire   
48                            Connectivity            Bandwidth   

   Need for replacement - (OFP) Availability - (OFP)  
0                           Yes        Need To Order  
1                           Yes        Need To Order  
2                           Yes        Need To Order  
3                           Yes        Need To Order  
4                            No            Available  
5                            No            Available  
6                           Yes        Need To Order  
7                            No            Available  
8                           Yes            Available  
9                           Yes            Available  
10                          Yes            Avai

In [6]:
# Save Encoder Objects for new incoming data
import pickle
encx0 = LabelEncoder().fit(X[:,0])
encx1 = LabelEncoder().fit(X[:,1])
encx2 = LabelEncoder().fit(X[:,2])
encx3 = LabelEncoder().fit(X[:,3])
filename = 'WIFI/WIFIencx0.sav'
pickle.dump(encx0,open(filename,'wb'))
filename = 'WIFI/WIFIencx1.sav'
pickle.dump(encx1,open(filename,'wb'))
filename = 'WIFI/WIFIencx2.sav'
pickle.dump(encx2,open(filename,'wb'))
filename = 'WIFI/WIFIencx3.sav'
pickle.dump(encx3,open(filename,'wb'))

In [7]:
data = ['Speed','Lan Wire','No','Available']

In [8]:
X[:,0] = encx0.transform(X[:,0])
X[:,1] = encx1.transform(X[:,1])
X[:,2] = encx2.transform(X[:,2])
X[:,3] = encx3.transform(X[:,3])

In [9]:
print(X)

[[0 3 1 1]
 [1 0 1 1]
 [0 3 1 1]
 [2 0 1 1]
 [0 2 0 0]
 [0 1 0 0]
 [2 0 1 1]
 [0 1 0 0]
 [0 2 1 0]
 [2 1 1 0]
 [2 1 1 0]
 [2 1 1 1]
 [0 3 1 1]
 [1 0 1 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 2 0 1]
 [0 1 0 1]
 [1 3 1 1]
 [1 1 0 0]
 [1 3 0 1]
 [0 2 0 0]
 [2 2 0 0]
 [0 1 0 1]
 [1 1 0 0]
 [2 0 1 0]
 [0 2 1 1]
 [2 3 1 1]
 [1 2 1 0]
 [1 0 1 0]
 [1 2 1 1]
 [2 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 1]
 [0 3 1 1]
 [0 1 1 1]
 [2 3 0 0]
 [2 3 0 0]
 [1 2 1 1]
 [1 2 0 1]
 [2 1 0 1]
 [2 0 0 0]
 [2 3 0 1]
 [2 2 0 0]
 [2 2 1 1]
 [2 3 1 0]
 [1 1 1 1]
 [0 0 1 0]]


In [10]:
onehotencoder = OneHotEncoder(categorical_features=[0,1,2,3])
onehenc = onehotencoder.fit(X)
filename = 'WIFI/WIFIonehenc.sav'
pickle.dump(onehenc,open(filename,'wb'))
X = onehenc.transform(X).toarray()
d = encx0.transform([data[0]])
data[0] = d[0]
d = encx1.transform([data[1]])
data[1] = d[0]
d = encx2.transform([data[2]])
data[2] = d[0]
d = encx3.transform([data[3]])
data[3] = d[0]
ar = np.array(data)
print(data)
ar = ar.reshape(1,-1)
kar=onehenc.transform(ar).toarray()
print(kar)
print(len(X[0]))

[2, 1, 0, 0]
[[0. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0.]]
11


In [11]:
k = list()
notlist = [0,3,7,9]
for i in range(11):
    if i not in notlist:
        k.append(i)
X = X[:,k]
kar = kar[:,k]

In [12]:
print((kar[0]))

[0. 1. 1. 0. 0. 0. 0.]


## SVR

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [15]:
model1 = SVR(kernel='rbf')
model1.fit(X_train,Y_train)
Y_pred = model1.predict(X_test)

In [16]:
Y_pred

array([7.69542036, 7.51286639, 7.70819342, 8.00382787, 7.82023588,
       7.19664558, 8.06425389, 8.09998536, 8.10057596, 7.57041253])

In [17]:
Y_test

array([ 6,  9,  5,  8,  7,  6,  7,  8,  8, 10])

In [18]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C':[1,10,100,1000], 'kernel': ['rbf'], 'gamma':[0.05,0.01,0.001,0.0001]},
             {'C':[100,200,300,400], 'kernel': ['poly'], 'gamma':[0.05,0.06,0.07,0.08,0.09,0.1]},
             {'C':[1,10,100,1000], 'kernel': ['sigmoid'], 'gamma':[0.05,0.01,0.001,0.0001]}]
gridsearch = GridSearchCV(estimator=model1,
                         param_grid=parameters,
                         scoring='r2',
                         cv=10)
gridsearch = gridsearch.fit(X_train,Y_train)
print(gridsearch.best_score_)
print(gridsearch.best_params_)

-0.1683974263841896
{'C': 1, 'gamma': 0.05, 'kernel': 'rbf'}


## Random Forest

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [20]:
model2 = RandomForestRegressor(n_estimators=700, criterion='mse',random_state=0)
model2 = model2.fit(X,Y)

In [21]:
from sklearn.metrics import r2_score
Y_pred = model2.predict(X)
for i in Y_pred:
    print(round(i))
print(Y_test)
print(r2_score(Y,Y_pred))

8.0
8.0
8.0
7.0
9.0
8.0
7.0
8.0
7.0
10.0
10.0
9.0
8.0
8.0
9.0
7.0
8.0
9.0
8.0
10.0
8.0
9.0
7.0
9.0
10.0
6.0
6.0
7.0
8.0
7.0
8.0
6.0
7.0
8.0
7.0
8.0
7.0
6.0
6.0
8.0
8.0
10.0
5.0
9.0
7.0
8.0
7.0
8.0
7.0
[ 6  9  5  8  7  6  7  8  8 10]
0.9152893136403127


In [22]:
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators':[1,10,100,1000], 'criterion':['mse','mae']}]
grid_search = GridSearchCV(estimator=model2,
                          param_grid=parameters,
                          scoring='r2',
                          cv=10)
grid_search = grid_search.fit(X,Y)
print(grid_search.best_score_)
print(grid_search.best_params_)

-0.47365223123878664
{'criterion': 'mae', 'n_estimators': 1000}


In [23]:
import pickle
filename = 'WIFI/WIFImodel.sav'
pickle.dump(model2,open(filename,'wb'))

In [24]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(kar)
print(result)
from sklearn.metrics import r2_score

[9.81142857]


In [25]:
from sklearn.preprocessing import LabelEncoder
c = ['France', 'UK', 'US', 'US', 'UK', 'China', 'France']
enc = LabelEncoder().fit(c)
encoded = enc.transform(c)
print(encoded)

enc.transform(['France'])


[1 2 3 3 2 0 1]


array([1])