In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
np.set_printoptions(threshold=np.inf)

In [35]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

## Fee Pay 

In [36]:
dataset = pd.read_csv('FeePay/FeePay.csv')
dataset

Grievance Subject Current Payement Status Mode of Transaction  \
0            Not Reqd               Processed              CHEQUE   
1            Not Reqd                 Pending             CHALLAN   
2            Not Reqd                  Failed              CHEQUE   
3            Not Reqd               Processed                NEFT   
4            Not Reqd               Processed              CHEQUE   
5            Not Reqd                 Pending                  DD   
6            Not Reqd               Processed                NEFT   
7            Not Reqd                 Pending               PAYTM   
8            Not Reqd                  Failed               PAYTM   
9            Not Reqd               Processed             CHALLAN   
10           Not Reqd                 Pending                  DD   
11           Not Reqd               Processed               PAYTM   
12           Not Reqd                  Failed             CHALLAN   
13           Not Reqd                  Failed                  DD   
14           Not Reqd               Processed               PAYTM   
15           Not Reqd                 Pending                  DD   
16           Not Reqd                  Failed              CHEQUE   
17           Not Reqd               Processed                NEFT   
18           Not Reqd                 Pending              CHEQUE   
19           Not Reqd               Processed               PAYTM   
20           Not Reqd                 Pending               PAYTM   
21           Not Reqd               Processed                  DD   
22           Not Reqd               Processed             CHALLAN   
23           Not Reqd                 Pending               PAYTM   
24           Not Reqd               Processed             CHALLAN   
25           Not Reqd               Processed                NEFT   
26           Not Reqd                  Failed              CHEQUE   
27           Not Reqd                 Pending              CHEQUE   
28           Not Reqd                  Failed                  DD   
29           Not Reqd                 Pending                NEFT   
30           Not Reqd               Processed                NEFT   
31           Not Reqd                  Failed             CHALLAN   
32           Not Reqd                  Failed                  DD   
33           Not Reqd               Processed             CHALLAN   
34           Not Reqd                 Pending                  DD   
35           Not Reqd                 Pending             CHALLAN   
36           Not Reqd               Processed             CHALLAN   
37           Not Reqd                  Failed              CHEQUE   
38           Not Reqd               Processed                  DD   
39           Not Reqd               Processed                  DD   
40           Not Reqd                 Pending              CHEQUE   
41           Not Reqd                 Pending              CHEQUE   
42           Not Reqd               Processed                NEFT   
43           Not Reqd                  Failed               PAYTM   
44           Not Reqd                 Pending               PAYTM   
45           Not Reqd               Processed              CHEQUE   
46           Not Reqd                 Pending               PAYTM   
47           Not Reqd                  Failed                  DD   
48           Not Reqd               Processed               PAYTM   

   Bank used by Payee  Account Number of Payee  Transaction Number  \
0               ICICI             910421000000          1043124973   
1                HDFC             993137000000          1624491109   
2                HDFC             916277000000          1146119231   
3                HDFC             990955000000          1121076158   
4                HDFC             962640000000          1875593324   
5               ICICI             949003000000          1757176082   
6               ICICI             909966000000          1410303

In [37]:
k = [1,2,3]
df = dataset.iloc[:, k] 
X = dataset.iloc[:, k].values
Y = dataset.iloc[:, 9].values
len(X[0])
df

Current Payement Status Mode of Transaction Bank used by Payee
0                Processed              CHEQUE              ICICI
1                  Pending             CHALLAN               HDFC
2                   Failed              CHEQUE               HDFC
3                Processed                NEFT               HDFC
4                Processed              CHEQUE               HDFC
5                  Pending                  DD              ICICI
6                Processed                NEFT              ICICI
7                  Pending               PAYTM              ICICI
8                   Failed               PAYTM                SBI
9                Processed             CHALLAN                SBI
10                 Pending                  DD              ICICI
11               Processed               PAYTM              ICICI
12                  Failed             CHALLAN               HDFC
13                  Failed                  DD                SBI
14               Processed               PAYTM              ICICI
15                 Pending                  DD              ICICI
16                  Failed              CHEQUE                SBI
17               Processed                NEFT                SBI
18                 Pending              CHEQUE               HDFC
19               Processed               PAYTM                SBI
20                 Pending               PAYTM              ICICI
21               Processed                  DD               HDFC
22               Processed             CHALLAN               HDFC
23                 Pending               PAYTM              ICICI
24               Processed             CHALLAN                SBI
25               Processed                NEFT               HDFC
26                  Failed              CHEQUE               HDFC
27                 Pending              CHEQUE                SBI
28                  Failed                  DD               HDFC
29                 Pending                NEFT              ICICI
30               Processed                NEFT               HDFC
31                  Failed             CHALLAN                SBI
32                  Failed                  DD                SBI
33               Processed             CHALLAN              ICICI
34                 Pending                  DD                SBI
35                 Pending             CHALLAN              ICICI
36               Processed             CHALLAN              ICICI
37                  Failed              CHEQUE               HDFC
38               Processed                  DD               HDFC
39               Processed                  DD              ICICI
40                 Pending              CHEQUE                SBI
41                 Pending              CHEQUE              ICICI
42               Processed                NEFT               HDFC
43                  Failed               PAYTM               HDFC
44                 Pending               PAYTM                SBI
45               Processed              CHEQUE                SBI
46                 Pending               PAYTM                SBI
47                  Failed                  DD                SBI
48               Processed               PAYTM              ICICI

In [38]:
# Save Encoder Objects for new incoming data
import pickle
encx0 = LabelEncoder().fit(X[:,0])
encx1 = LabelEncoder().fit(X[:,1])
encx2 = LabelEncoder().fit(X[:,2])
filename = 'FeePay/FeePayencx0.sav'
pickle.dump(encx0,open(filename,'wb'))
filename = 'FeePay/FeePayencx1.sav'
pickle.dump(encx1,open(filename,'wb'))
filename = 'FeePay/FeePayencx2.sav'
pickle.dump(encx2,open(filename,'wb'))

In [39]:
data = ['Failed','PAYTM','ICICI']

In [40]:
X[:,0] = encx0.transform(X[:,0])
X[:,1] = encx1.transform(X[:,1])
X[:,2] = encx2.transform(X[:,2])

In [41]:
print(max(X[:,2]))

2


In [42]:
onehotencoder = OneHotEncoder(categorical_features=[0,1,2])
onehenc = onehotencoder.fit(X)
filename = 'FeePay/FeePayonehenc.sav'
pickle.dump(onehenc,open(filename,'wb'))
X = onehenc.transform(X).toarray()
d = encx0.transform([data[0]])
data[0] = d[0]
d = encx1.transform([data[1]])
data[1] = d[0]
d = encx2.transform([data[2]])
data[2] = d[0]
ar = np.array(data)
print(data)
ar = ar.reshape(1,-1)
kar=onehenc.transform(ar).toarray()
print(kar)
print(len(X[0]))

[0, 4, 1]
[[1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]]
11


In [43]:
k = list()
notlist = [0,3,8]
for i in range(11):
    if i not in notlist:
        k.append(i)
X = X[:,k]
kar = kar[:,k]

In [44]:
print(len(X[0]))

8


## SVR

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [47]:
model1 = SVR(kernel='rbf')
model1.fit(X_train,Y_train)
Y_pred = model1.predict(X_test)

In [48]:
Y_pred

array([5.96286244, 5.29738679, 5.22568211, 5.33099353, 5.10049781,
       5.22568211, 5.50242929, 5.39705711, 6.09975361, 6.09289689])

In [49]:
Y_test

array([8, 3, 5, 5, 5, 5, 4, 7, 6, 4])

In [50]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C':[1,10,100,1000], 'kernel': ['rbf'], 'gamma':[0.05,0.01,0.001,0.0001]},
             {'C':[100,200,300,400], 'kernel': ['poly'], 'gamma':[0.05,0.06,0.07,0.08,0.09,0.1]},
             {'C':[1,10,100,1000], 'kernel': ['sigmoid'], 'gamma':[0.05,0.01,0.001,0.0001]}]
gridsearch = GridSearchCV(estimator=model1,
                         param_grid=parameters,
                         scoring='r2',
                         cv=10)
gridsearch = gridsearch.fit(X_train,Y_train)
print(gridsearch.best_score_)
print(gridsearch.best_params_)

-0.6349329093127106
{'C': 300, 'gamma': 0.07, 'kernel': 'poly'}


## Random Forest

In [51]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [52]:
model2 = RandomForestRegressor(n_estimators=100, criterion='mse',random_state=0)
model2 = model2.fit(X,Y)

In [53]:
from sklearn.metrics import r2_score
Y_pred = model2.predict(X)
for i in Y_pred:
    print(round(i))
print(Y_test)
print(r2_score(Y,Y_pred))

5.0
7.0
5.0
5.0
4.0
4.0
7.0
6.0
4.0
5.0
4.0
6.0
8.0
5.0
6.0
4.0
6.0
5.0
5.0
5.0
6.0
7.0
8.0
6.0
5.0
5.0
5.0
7.0
7.0
8.0
5.0
4.0
5.0
10.0
5.0
8.0
10.0
5.0
7.0
6.0
7.0
6.0
5.0
5.0
6.0
4.0
6.0
5.0
6.0
[8 3 5 5 5 5 4 7 6 4]
0.9320473691776884


In [54]:
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators':[1,10,100,1000], 'criterion':['mse']}]
grid_search = GridSearchCV(estimator=model2,
                          param_grid=parameters,
                          scoring='r2',
                          cv=10)
grid_search = grid_search.fit(X,Y)
print(grid_search.best_score_)
print(grid_search.best_params_)

0.1126049629473752
{'criterion': 'mse', 'n_estimators': 100}


In [55]:
import pickle
filename = 'FeePay/FeePaymodel.sav'
pickle.dump(model2,open(filename,'wb'))

In [56]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(kar)
print(result)
from sklearn.metrics import r2_score

[5.92]


In [57]:
from sklearn.preprocessing import LabelEncoder
c = ['France', 'UK', 'US', 'US', 'UK', 'China', 'France']
enc = LabelEncoder().fit(c)
encoded = enc.transform(c)
print(encoded)

enc.transform(['France'])


[1 2 3 3 2 0 1]


array([1])

In [58]:
data = pd.read_csv('Mess(hr)/Mess(hr).csv')

In [59]:
d = data.iloc[:,1].values
set(d)

{'A', 'B', 'E', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'PG'}

## Classifier

In [60]:
Y2 = dataset.iloc[:,-1].values

In [61]:
from sklearn.ensemble import RandomForestClassifier

In [82]:
classifier = RandomForestClassifier(n_estimators=750, criterion='entropy')

In [83]:
classifier = classifier.fit(X,Y2)

In [84]:
y_pred = classifier.predict(X)

In [85]:
y_pred


array(['Major ', 'Minor', 'Minor', 'Minor', 'Major ', 'Major ', 'Major ',
       'Minor', 'Minor', 'Minor', 'Major ', 'Major ', 'Minor', 'Minor',
       'Major ', 'Major ', 'Minor', 'Minor', 'Major ', 'Major ', 'Minor',
       'Minor', 'Minor', 'Minor', 'Minor', 'Minor', 'Minor', 'Minor',
       'Major ', 'Minor', 'Minor', 'Minor', 'Minor', 'Major ', 'Minor',
       'Minor', 'Major ', 'Minor', 'Minor', 'Minor', 'Minor', 'Major ',
       'Minor', 'Minor', 'Minor', 'Minor', 'Minor', 'Minor', 'Major '],
      dtype=object)

In [86]:
from sklearn.metrics import classification_report

In [87]:
print(classification_report(Y2,y_pred))

             precision    recall  f1-score   support

     Major        0.93      0.70      0.80        20
      Minor       0.82      0.97      0.89        29

avg / total       0.87      0.86      0.85        49



In [88]:
parameters = [{'n_estimators':[1,10,100,1000], 'criterion':['gini', 'entropy']}]
grid_search = GridSearchCV(estimator=classifier,
                          param_grid=parameters,
                          scoring='accuracy',
                          cv=10)
grid_search = grid_search.fit(X,Y)
print(grid_search.best_score_)
print(grid_search.best_params_)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


0.673469387755102
{'criterion': 'gini', 'n_estimators': 10}


In [89]:
filename = 'FeePay/FeePayClassmodel.sav'
pickle.dump(classifier,open(filename,'wb'))