In [417]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
np.set_printoptions(threshold=np.inf)

In [418]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

## Scholarship Portal 

In [419]:
dataset = pd.read_csv('scholarship_portal/scholarship_portal.csv')
dataset

Grievance Subject Area/Screen of Error - (OFP) Degree of Error - (OFP)  \
0           Not Reqd                    DashBoard                     Low   
1           Not Reqd                        Login                Moderate   
2           Not Reqd                    DashBoard                     Low   
3           Not Reqd                    DashBoard                Moderate   
4           Not Reqd                         Home                    High   
5           Not Reqd                    DashBoard                Moderate   
6           Not Reqd                         Home                    High   
7           Not Reqd                        Login                Moderate   
8           Not Reqd                        Login                    High   
9           Not Reqd                    DashBoard                     Low   
10          Not Reqd                    DashBoard                Moderate   
11          Not Reqd                        Login                    High   
12          Not Reqd                        Login                    High   
13          Not Reqd                    DashBoard                Moderate   
14          Not Reqd                         Home                     Low   
15          Not Reqd                    DashBoard                Moderate   
16          Not Reqd                        Login                Moderate   
17          Not Reqd                    DashBoard                     Low   
18          Not Reqd                    DashBoard                    High   
19          Not Reqd                    DashBoard                     Low   
20          Not Reqd                        Login                     Low   
21          Not Reqd                         Home                    High   
22          Not Reqd                        Login                    High   
23          Not Reqd                        Login                    High   
24          Not Reqd                         Home                     Low   
25          Not Reqd                        Login                Moderate   
26          Not Reqd                        Login                     Low   
27          Not Reqd                    DashBoard                    High   
28          Not Reqd                        Login                     Low   
29          Not Reqd                    DashBoard                    High   
30          Not Reqd                         Home                     Low   
31          Not Reqd                    DashBoard                     Low   
32          Not Reqd                    DashBoard                Moderate   
33          Not Reqd                         Home                    High   
34          Not Reqd                        Login                Moderate   
35          Not Reqd                    DashBoard                     Low   
36          Not Reqd                         Home                    High   
37          Not Reqd                        Login                    High   
38          Not Reqd                         Home                Moderate   
39          Not Reqd                        Login                     Low   
40          Not Reqd                        Login                     Low   
41          Not Reqd                        Login                     Low   
42          Not Reqd                         Home                Moderate   
43          Not Reqd                        Login                Moderate   
44          Not Reqd                         Home                    High   
45          Not Reqd                        Login                Moderate   
46          Not Reqd                    DashBoard                     Low   
47          Not Reqd                    DashBoard                    High   
48          Not Reqd                         Home                    High   

   Grievance Description Attached Documents  Days till Response  
0               Not Reqd           Not Reqd                   6  
1               Not 

In [420]:
X = dataset.iloc[:, 1:3].values
Y = dataset.iloc[:, 5].values

In [421]:
# Save Encoder Objects for new incoming data
import pickle
encx0 = LabelEncoder().fit(X[:,0])
encx1 = LabelEncoder().fit(X[:,1])
filename = 'scholarship_portal/scholarship_portalencx0.sav'
pickle.dump(encx0,open(filename,'wb'))
filename = 'scholarship_portal/scholarship_portalencx1.sav'
pickle.dump(encx1,open(filename,'wb'))

In [422]:
data = ['Login','Low']

In [423]:
X[:,0] = encx0.transform(X[:,0])
X[:,1] = encx1.transform(X[:,1])
onehotencoder = OneHotEncoder(categorical_features=[0,1])
onehenc = onehotencoder.fit(X)
filename = 'scholarship_portal/scholarship_portalonehenc.sav'
pickle.dump(onehenc,open(filename,'wb'))
X = onehenc.transform(X).toarray()
d = encx0.transform([data[0]])
data[0] = d[0]
d = encx1.transform([data[1]])
data[1] = d[0]
ar = np.array(data)
print(data)
ar = ar.reshape(1,-1)
kar=onehenc.transform(ar).toarray()
print(kar)
print(len(X[0]))

[2, 1]
[[0. 0. 1. 0. 1. 0.]]
6


In [424]:
k = list()
for i in range(6):
    if i!=0 and i!=3:
        k.append(i)
X = X[:,k]
kar = kar[:,k]

In [425]:
print(len(X[0]))

4


## SVR

In [426]:
from sklearn.model_selection import train_test_split

In [427]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [428]:
model1 = SVR(kernel='rbf')
model1.fit(X_train,Y_train)
Y_pred = model1.predict(X_test)

In [429]:
Y_pred

array([5.98144496, 5.10008932, 5.1000895 , 5.20373166, 6.44128554,
       5.48819099, 5.15367493, 5.1000895 , 5.15367493, 6.44128554])

In [430]:
Y_test

array([5, 5, 5, 6, 7, 6, 5, 5, 5, 7])

In [431]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C':[1,10,100,1000], 'kernel': ['rbf'], 'gamma':[0.05,0.01,0.001,0.0001]},
             {'C':[100,200,300,400], 'kernel': ['poly'], 'gamma':[0.05,0.06,0.07,0.08,0.09,0.1]},
             {'C':[1,10,100,1000], 'kernel': ['sigmoid'], 'gamma':[0.05,0.01,0.001,0.0001]}]
gridsearch = GridSearchCV(estimator=model1,
                         param_grid=parameters,
                         scoring='r2',
                         cv=10)
gridsearch = gridsearch.fit(X_train,Y_train)
print(gridsearch.best_score_)
print(gridsearch.best_params_)

0.5346342406556329
{'C': 400, 'gamma': 0.1, 'kernel': 'poly'}


## Random Forest

In [448]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [449]:
model2 = RandomForestRegressor(n_estimators=910, criterion='mae',random_state=0)
model2 = model2.fit(X,Y)

In [450]:
Y_pred = model2.predict(X_test)
print(Y_pred)
print(Y_test)

[5.18681319 5.02087912 5.04505495 5.7489011  6.9478022  5.97527473
 5.02472527 5.04505495 5.02472527 6.9478022 ]
[5 5 5 6 7 6 5 5 5 7]


In [447]:
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators':[900,910,920,930,940,950], 'criterion':['mae']}]
grid_search = GridSearchCV(estimator=model2,
                          param_grid=parameters,
                          scoring='r2',
                          cv=10)
grid_search = grid_search.fit(X,Y)
print(grid_search.best_score_)
print(grid_search.best_params_)

0.7148648658619864
{'criterion': 'mae', 'n_estimators': 910}


In [451]:
import pickle
filename = 'scholarship_portal/scholarship_portalmodel.sav'
pickle.dump(model2,open(filename,'wb'))

In [452]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(kar)
print(result)
from sklearn.metrics import r2_score
print(r2_score(Y_test,Y_pred))

[5.04505495]
0.9828548597693515


In [250]:
from sklearn.preprocessing import LabelEncoder
c = ['France', 'UK', 'US', 'US', 'UK', 'China', 'France']
enc = LabelEncoder().fit(c)
encoded = enc.transform(c)
print(encoded)

enc.transform(['France'])


[1 2 3 3 2 0 1]


array([1])